{% set name = "generic_parser" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/generic_parser-{{ version }}.tar.gz
  sha256: dd51a23a95ade4509608580e80c0eb882998ca0a61be751453644a5200270766

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - generic_parser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pylhc/generic_parser
  summary: A parser for arguments and config-files that also allows direct python input.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A parser for arguments and config files that also allows direct Python input.
  doc_url: https://pylhc.github.io/generic_parser/

extra:
  recipe-maintainers:
    - fsoubelet
